config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users,only: [:show,:index,:edit,:update] do
  resources :follows, only: [:index]
  resources :followers, only: [:index]
  end
  resources :relationships, only: [:create, :destroy]
  resources :books do
  	resource :favorites, only: [:create, :destroy]
  	resources :book_comments, only: [:create, :destroy]
  end
  get 'home/about'
    root :to =>'home#top'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	 has_many :favorites, dependent: :destroy
  		def favorited_by?(user)
    		favorites.where(user_id: user.id).exists?
  		end

  	 has_many :book_comments, dependent: :destroy

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/follow.rb
class Follow < ApplicationRecord

  belongs_to :user

end

app/models/follower.rb
class Follower < ApplicationRecord

	belongs_to :user

end

app/models/relationship.rb
class Relationship < ApplicationRecord

	belongs_to :user, class_name: 'User'

	belongs_to :follow, class_name: 'User'

	validates :user_id, presence: true

	validates :follow_id, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books, dependent: :destroy
  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, {length: {maximum: 50}}

  has_many :favorites, dependent: :destroy
  has_many :book_comment, dependent: :destroy

  #能動的関係
  has_many :relationships, dependent: :destroy,foreign_key: 'user_id'
  has_many :followings, through: :relationships, source: :follow

  #受動的関係
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id', dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!

  before_action :correct_user, only: [:edit, :update ,:destroy]

  def show
    @book = Book.new
    @book_p = Book.find(params[:id])
    @user = @book_p.user
    @book_comment = BookComment.new
  end

  def index
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
    @book = Book.find(params[:id])
  end



  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def correct_user
    @book_show = Book.find(params[:id])
    if current_user != @book_show.user
       redirect_to books_path
    end
  end


end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
  	user = current_user
  	book = Book.find(params[:book_id])
  	favorite = current_user.favorites.new(book_id: book.id)
  	favorite.save
  	redirect_to request.referer
  end

  def destroy
  	user = current_user
  	book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_to request.referer
  end

end

app/controllers/followers_controller.rb
class FollowersController < ApplicationController

  def index
  	@user = User.find(params[:user_id])
  end

end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def index
  	@user = User.find(params[:user_id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update]

  def show
    @user = User.find(params[:id])
    @books = Book.all
    @book = Book.new
    @users = User.all
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/followers_helper.rb
module FollowersHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %>
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
	<% if book.errors.any? %>
	  <h3><%= book.errors.count %>error occurrence</h3>
       <div class="alert alert-warning">
         <ul>
           <% book.errors.full_messages.each do |message| %>
             <li><%= message %></li>
           <% end %>
         </ul>
       </div>
    <% end %>
<% end %>

app/views/books/edit.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-3">

		<h1>Editing Book</h1>

	      <% if @book.errors.any? %>
		    <div class="alert alert-warning">
		      <ul>
		        <% @book.errors.full_messages.each do |message| %>
		          <li><%= message %></li>
		        <% end %>
		      </ul>
		    </div>
		  <% end %>

		<%= render "books/newform", book: @book %>
		<%= link_to "Show", book_path(@book), class: "book_#{@book.id}" %>
		<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
					<td>
					  <% if book.favorited_by?(current_user) %>
						<%= link_to book_favorites_path(book), method: :delete do %>
						  <i class="fa fa-heart" aria-hidden="true" style="color: gray;"></i>
						  <%= book.favorites.count %>
						<% end %>
					  <% else %>
						<%= link_to book_favorites_path(book), method: :post do %>
						  <i class="fa fa-heart-o" aria-hidden="true"></i>
						  <%= book.favorites.count %>
						<% end %>
				      <% end %>
				    </td>
				    <td>コメント数:<%= book.book_comments.count %></td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to user_path(@book_p.user) do %>
							<%= attachment_image_tag(@book_p.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book_p.user.name %>
						<% end %>
					</td>
					<td><%= link_to @book_p.title, book_path(@book_p) %></td>
					<td><%= @book_p.body %></td>
					<td><% if @book_p.favorited_by?(current_user) %>
					  <%= link_to book_favorites_path(@book_p), method: :delete do %>
					    <i class="fa fa-heart" aria-hidden="true" style="color: gray;"></i>
					    <%= @book_p.favorites.count %>
					  <% end %>
					  <% else %>
					  <%= link_to book_favorites_path(@book_p), method: :post do %>
					    <i class="fa fa-heart-o" aria-hidden="true"></i>
					    <%= @book_p.favorites.count %>
					  <% end %>
					<% end %></td>
					<td>コメント数:<%= @book_p.book_comments.count %></td>
				  <% if @user == current_user %>
					<td><%= link_to "Edit", edit_book_path(@book_p), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
					<td><%= link_to "Destroy", book_path(@book_p), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book_p.id}" %></td>
				  <% end %>
				</tr>
		</table>

			<table>
					<% @book_p.book_comments.each do |book_comment| %>
					<tr>
					<td>
						<%= link_to user_path(@book_p.user) do %>
							<%= attachment_image_tag(@book_p.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= book_comment.user.name %>
						<% end %>
					</td>
					<td>
						<%= book_comment.comment %>
						<% if @user == current_user %>
						<%= link_to "destroy", book_book_comment_path(book_comment.book, book_comment), method: :delete, class: "btn-sm btn-danger destroy_book_#{@book_p.id}" %>
						<% end %>
					</td>
					<% end %>
				</tr>
			</table>
			<%= form_for [@book_p, @book_comment] do |f| %>
				<div>
					<%= f.text_area :comment, rows:'5', class: "form-control" %>
					<%= f.submit "送信", class: "pull-right" %>
				</div>
			<% end %>

	</div>
</div>

app/views/followers/index.html.erb
<h2>Follower Users</h2>

<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @user.followers.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>
				<td>フォロー数:<%= user.followings.count %></td>
				<td>フォロワー数:<%= user.followers.count %></td>

				<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

app/views/follows/index.html.erb
<h2>Follow Users</h2>

<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @user.followings.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>
				<td>フォロー数:<%= user.followings.count %></td>
				<td>フォロワー数:<%= user.followers.count %></td>

				<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>
	<tr>
		<th>follows</th>
		<th>
			<%= link_to user_follows_path(user) do %>
			<%= user.followings.count %>
			<% end %>
		</th>
	</tr>
	<tr>
		<th>followers</th>
		<th>
			<%= link_to user_followers_path(user) do %>
			<%= user.followers.count %>
			<% end %>
		</th>
	</tr>
</table>
<% if user.id == current_user.id %>
<div class="row">
	<%= link_to '', edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>
<% end %>

<%= render 'relationships/follow_button', user: user %>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

	<!-- エラーメッセージ表示-->
	<% if @user.errors.any? %>
		<div id="error_explanation">
			<h3><%= @user.errors.count %>error prohibited this obj from being saved:</h3><
			<ul>
				<% @user.errors.full_messages.each do |message| %>
				<li><%= message %></li>
				<% end %>
			</ul>
		</div>
	<% end %>
	<!-- エラーメッセージ表示-->

	<div class="field">
		<%= f.label :name %>
		<%= f.text_field :name, class: "name" %>
	</div>

	<div class="field">
		<%= f.label :image %>
		<%= f.attachment_field :profile_image, class: "user_image" %>
	</div>

	<div class="field">
		<%= f.label :introduction %>
		<%= f.text_area :introduction, class: "introduction" %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
  <div class="col-xs-3">
	<h2>User info</h2>
	<%= render 'users/profile', user: current_user %>

	<h2>New book</h2>
	<%= render 'books/newform', book: @book %>
  </div>

  <div class="col-xs-9">
	<h2>Users</h2>
	<!--users一覧 -->
	<table class="table">
		<thead>
			<tr>
				<th>image</th>
				<th>name</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<tbody>
			<% @users.each do |user| %>
			<tr>
				<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
				<td><%= user.name %></td>
				<td><%= link_to "Show", user_path(user), class: "user_#{user.id}" %></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	<!--users一覧 -->
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">
		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>
	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>